version: "3"

services:
  mongo:
    image: mongo:3.6.2-jessie
    container_name: interlink-gamification-mongo
    ports:
      - "50000:27017"
    volumes:
      - mongo-data:/data/db
  gamification-engine:
    build:
      context: .
    container_name: interlink-gamification-engine
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    env_file: interlink-gamification.env
    volumes:
      - ./logs:/app/interlink-gamification/logs
volumes:
  mongo-data:
