

server:
    port: ${SERVER_PORT:8080}
    servlet:
      context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data: 
    mongodb: 
      host: localhost
      port: 27017
      database: interlink-gamification
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

import: 
  dir: /Users/mtrainotti/dev

export: 
  dir: /Users/mtrainotti/dev


#
# RABBITMQ CONFIGURATIONS
#

rabbitmq: 
  enabled: ${RABBITMQ_ENABLED:true}
  host: ${RABBITMQ_HOST:localhost}
  virtualhost: ${RABBITMQ_VIRTUALHOST:interlink}
  port: ${RABBITMQ_PORT:5672}
  user: ${RABBITMQ_USER:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  pngExchangeName: ${RABBITMQ_PNGEXCHANGENAME:ge-notifications}
  pngRoutingKeyPrefix: ${RABBITMQ_PNGROUTINGKEYPREFIX:game}