

server:
    port: ${SERVER_PORT:8080}
    servlet:
      context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data: 
    mongodb:
     uri: ${SPRING_DATA_MONGODB_URL:mongodb://localhost:27017/interlink-gamification}
     database: ${MONGO_DBNAME:interlink-gamification}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

import: 
  dir: ${IMPORT_DIR:/home/dev/gamification/interlink}

export: 
  dir: /home/dev/gamification/interlink
