package eu.trentorise.game.model

import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;

rule "update_development_points"
when
    InputData( $development : data["development"])
    InputData( $devComplexity: data["devComplexity"]);
    $pc : PointConcept(name == "development")
then
    utils.log("apply \'update development points\'");
    Double development = $development != null ? (Double) $development : 0;
    Double devComplexity = $devComplexity != null ? (Double) $devComplexity : 0;

    
    $pc.setScore($pc.getScore() + (development * devComplexity));
    update($pc);
end